package com.deepali.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// This is the server for our App

// This was generated by Spring Initializr

// ------------ DO NOT CHANGE!!!! ----------------


@SpringBootApplication
public class Bd6FirstSpringBootProjectApplication { // Tells the server this is a Spring Boot Application

	public static void main(String[] args) {
		SpringApplication.run(Bd6FirstSpringBootProjectApplication.class, args);
	}

}
